# 
# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "brach-pull-request"  ]


#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  
    
    - name: Instala las dependencias de nodes
      run: npm ci

    - name: Construir aplicación (si el script existe)
      run: npm run build --if-present

    - name: Ejecutar pruebas
      run: npm test
